-- 数据库: tg_gc
-- 账号管理表

CREATE TABLE IF NOT EXISTS `tg_telethon_account` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `phone` varchar(32) NOT NULL COMMENT '手机号',
    `api_id` int(11) DEFAULT NULL COMMENT 'Telegram API ID',
    `api_hash` varchar(64) DEFAULT NULL COMMENT 'Telegram API Hash',
    `tg_user_id` bigint(20) DEFAULT NULL COMMENT 'Telegram用户ID',
    `nickname` varchar(128) DEFAULT NULL COMMENT '昵称(firstName + lastName)',
    `username` varchar(64) DEFAULT NULL COMMENT '用户名',
    `country` varchar(100) DEFAULT NULL COMMENT '手机号归属国',
    `device_model` varchar(200) DEFAULT NULL COMMENT '设备型号',
    `system_version` varchar(100) DEFAULT NULL COMMENT '系统版本',
    `app_version` varchar(100) DEFAULT NULL COMMENT 'APP版本',
    `lang_code` varchar(20) DEFAULT NULL COMMENT '语言代码',
    `system_lang_code` varchar(20) DEFAULT NULL COMMENT '系统语言代码',
    `batch_no` varchar(64) DEFAULT NULL COMMENT '导入批次号',
    `status` varchar(20) NOT NULL DEFAULT 'offline' COMMENT '状态: online/offline/banned/restricted/failed/login1/login2',
    `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
    `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否已删除',
    `proxy_ip_id` int(11) DEFAULT NULL COMMENT '代理IP的ID',
    `proxy_group_no` varchar(64) DEFAULT NULL COMMENT '代理IP组号',
    `proxy_url` varchar(500) DEFAULT NULL COMMENT '完整代理URL',
    `proxy_protocol` varchar(10) DEFAULT NULL COMMENT '代理协议(socks5/http)',
    `proxy_host` varchar(200) DEFAULT NULL COMMENT '代理地址',
    `proxy_port` int(11) DEFAULT NULL COMMENT '代理端口',
    `proxy_username` varchar(200) DEFAULT NULL COMMENT '代理认证用户名',
    `proxy_password` varchar(200) DEFAULT NULL COMMENT '代理认证密码',
    `auto_reply` tinyint(1) DEFAULT '1' COMMENT '是否开启自动回复',
    `is_restricted` tinyint(1) DEFAULT '0' COMMENT '是否被限制',
    `total_msg_count` int(11) DEFAULT '0' COMMENT '消息总数',
    `sent_msg_count` int(11) DEFAULT '0' COMMENT '发送总数',
    `recv_msg_count` int(11) DEFAULT '0' COMMENT '接收总数',
    `node_id` varchar(32) DEFAULT NULL COMMENT '账号所属节点ID',
    `json_content` text COMMENT '账号JSON文件内容',
    `session_content` longblob COMMENT '账号session文件内容(二进制)',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_phone` (`phone`),
    KEY `idx_status` (`status`),
    KEY `idx_node_id` (`node_id`),
    KEY `idx_batch_no` (`batch_no`),
    KEY `idx_node_status` (`node_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Telethon账号管理表';
